version: '3.8'

# name: librarylens

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - db
      - redis
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./extracted_data
        target: /app/extracted_data
    networks:
      - librarylens-network
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/librarylens
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - ALLOWED_ORIGINS=http://localhost,http://localhost:80,http://44.200.215.2,http://library-lens.com,https://library-lens.com

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - SKIP_TYPECHECKING=true
        - VITE_API_URL=http://backend:8000/api/v1
    restart: always
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - librarylens-network

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=librarylens
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - librarylens-network

  redis:
    image: redis:7
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - librarylens-network

volumes:
  postgres_data:
    # name: librarylens-postgres-data

networks:
  librarylens-network:
    # name: librarylens-network
    driver: bridge 