version: '3'

# name: librarypulse

services:
  backend:
    build: 
      context: ./backend
    restart: always
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - ./backend/.env.docker:/app/.env
    networks:
      - librarypulse-network

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=librarypulse
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - librarypulse-network

  redis:
    image: redis:7
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - librarypulse-network

  # Uncomment when frontend is ready
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "5174:5173"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend
  #   networks:
  #     - librarypulse-network

volumes:
  postgres_data:
    # name: librarypulse-postgres-data

networks:
  librarypulse-network:
    # name: librarypulse-network
    driver: bridge 