name: AWS Credentials Test Only

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-aws-only:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Explicitly setting region
    
    - name: Test AWS Connectivity
      run: |
        # Install AWS CLI
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        
        echo "Testing basic AWS connectivity..."
        aws sts get-caller-identity
        
        echo "Testing Lightsail API access..."
        aws lightsail get-regions
        
        echo "Testing Lightsail instance listing..."
        aws lightsail get-instances || true  # Continue even if no instances exist
        
        echo "AWS Credentials test complete." 