name: AWS Credentials Test Only

on:
  workflow_dispatch:  # Only manual trigger
  # Explicitly prevent other triggers
  push:
    branches:
      - '**'
    paths-ignore:
      - '**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**'

jobs:
  test-aws-only:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Explicitly setting region
    
    - name: Test AWS Connectivity
      run: |
        echo "Testing basic AWS connectivity..."
        aws sts get-caller-identity
        
        echo "Checking current IAM policy..."
        aws iam list-attached-user-policies --user-name github-actions-deployer
        aws iam list-user-policies --user-name github-actions-deployer
        
        echo "Testing Lightsail API access..."
        aws lightsail get-regions --debug || {
          echo "Failed to get regions. Checking IAM permissions..."
          aws iam get-user-policy --user-name github-actions-deployer --policy-name github-actions-policy || true
          exit 1
        }
        
        echo "Testing Lightsail instance listing..."
        aws lightsail get-instances || true  # Continue even if no instances exist
        
        echo "AWS Credentials test complete." 