name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
    
    - name: Create .env file
      run: |
        cat > .env << EOL
        # Database Configuration
        DATABASE_URL=postgresql://postgres:postgres@localhost:5433/librarylens
        TEST_DATABASE_URL=postgresql://postgres:postgres@localhost:5433/librarylens_test

        # Redis Configuration
        REDIS_URL=redis://localhost:6380/0

        # Security
        SECRET_KEY=your-secret-key-here
        ACCESS_TOKEN_EXPIRE_MINUTES=30

        # Environment
        ENVIRONMENT=production
        DEBUG=false

        # CORS
        CORS_ORIGINS=http://localhost:5173,http://localhost:3000

        # Email Configuration
        EMAILS_ENABLED=true
        SMTP_HOST=smtp.gmail.com
        SMTP_PORT=587
        SMTP_TLS=true
        SMTP_USER=your-email@gmail.com
        SMTP_PASSWORD=your-app-password
        EMAILS_FROM_EMAIL=your-email@gmail.com
        EMAILS_FROM_NAME=Library Lens

        # Admin User
        ADMIN_EMAIL=admin@example.com
        ADMIN_PASSWORD=changeme
        ADMIN_FIRST_NAME=Admin
        ADMIN_LAST_NAME=User
        EOL
    
    - name: Deploy to Production
      run: |
        # Copy application files
        scp -i ~/.ssh/deploy_key -r ./* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/opt/projects/librarylens/
        
        # Update VPS configuration and restart the application
        ssh -i ~/.ssh/deploy_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} '
          cd /opt/projects/librarylens
          chmod +x update-vps.sh
          ./update-vps.sh
        '
    
    - name: Cleanup
      if: always()
      run: rm -f ~/.ssh/deploy_key 