name: Test AWS Credentials

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-aws:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Explicitly setting region
    
    - name: Test AWS Connectivity
      run: |
        echo "Testing basic AWS connectivity..."
        aws sts get-caller-identity
        
        echo "Testing Lightsail API access..."
        aws lightsail get-regions
        
        echo "Testing Lightsail instance listing..."
        aws lightsail get-instances || true  # Continue even if no instances exist
        
        echo "AWS Credentials test complete." 