name: Test AWS Credentials

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-aws:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Explicitly setting region
    
    - name: Test Lightsail Access
      run: |
        # Test AWS connectivity
        echo "Testing AWS connectivity..."
        aws sts get-caller-identity
        
        # Test Lightsail permissions
        echo "Testing Lightsail access..."
        aws lightsail get-instances
        
        echo "Testing instance access..."
        aws lightsail get-instance-access-details --instance-name LibraryPulse 