name: Verify AWS Access

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  verify-aws-access:
    name: Verify AWS Access
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Test AWS Connectivity
      run: |
        echo "Testing basic AWS connectivity..."
        aws sts get-caller-identity
        
        echo "Testing Lightsail API access..."
        aws lightsail get-regions || {
          echo "Failed to get regions. Checking IAM permissions..."
          aws iam list-attached-user-policies --user-name github-actions-deployer
          aws iam list-user-policies --user-name github-actions-deployer
          exit 1
        } 